Develop
HRODEV/project7_8 pull request #24
Opened 2017-07-04 11:07 UTC by n9iels

2017-07-04 21:24 UTC, barld requested changes

2017-07-04 21:24 UTC, barld commented on PostManTests/web.postman_collection.json
> +{
Heeft uitbreiding nodig

2017-07-04 21:24 UTC, barld commented on PostManTests/web.postman_collection.json
> +{
Goed begin 👍

2017-07-04 21:24 UTC, barld commented on dbActions/declarationsActions_test.go
>  	var declaration []models.Declaration
enkelvoud terwijl je meerdere items ophaalt

2017-07-04 21:24 UTC, barld commented on dbActions/userActions.go
> +		return errors.New("No valid password or email given. Pasword must be at least 8 characters")
Er van uit gaande dat dit het enige is waar op gecheckt wordt biedt mogelijk problemen bij uitbreidingen in de toekomst

2017-07-04 21:24 UTC, barld commented on dbActions/userActions.go
> +		return errors.New("No valid password or email given. Pasword must be at least 8 characters")
zou ook moeten checken op dubbele email adressen

2017-07-04 21:24 UTC, barld commented on main.go
> +func insertTestData(db *gorm.DB) {
Weet het zelf gedaan maar zou nog even moeten worden gesplitst naar een apart bestand

2017-07-04 21:24 UTC, barld commented on routes/user.go
> +	tokenString, err := token.SignedString([]byte("gXV6aSf4NJ7Ah@S!DrE5$Pm!"))
On GitHub?!?! :octocat:

2017-07-04 21:24 UTC, barld commented on routes/user.go
>  func UserAuthGet(w http.ResponseWriter, r *http.Request, utils Utils) interface{} {
valt misschien op te spiltsen zodat het beter valt te testen en te hergebruiken

2017-07-04 21:24 UTC, barld commented on routes/user.go
> +	claims := token.Claims.(jwt.MapClaims)
waar gebruik je die map voor behalve om twee keer een waarde naar toe te schrijven?

2017-07-04 21:24 UTC, barld commented on services/auth.go
> +type AuthService struct {
een lege struct want?

2017-07-05 07:19 UTC, n9iels commented on dbActions/userActions.go
> +		return errors.New("No valid password or email given. Pasword must be at least 8 characters")
Hoe bedoel je "dubbele email adressen"?

2017-07-05 07:21 UTC, n9iels commented on routes/user.go
> +	claims := token.Claims.(jwt.MapClaims)
Deze wordt gebruik in het token dat gegenereerd is. Dus de claim die in deze map komen worden aan het token toegevoegd. Dat zijn in dit geval `exp` waarin de tijd in de vorm van UNIX timestamp staat tot wanneer het token geldig is, en `sub` waarin het userID van de gebruiker staat.

2017-07-05 07:21 UTC, n9iels commented on routes/user.go
> +	tokenString, err := token.SignedString([]byte("gXV6aSf4NJ7Ah@S!DrE5$Pm!"))
misschien even in een apart bestandje doen ja..... :sweat_smile:

2017-07-05 07:23 UTC, n9iels commented on services/auth.go
> +type AuthService struct {
Deze wordt hier gebruik https://github.com/HRODEV/project7_8/blob/develop/routes/user.go#L54 Had ik even snel gedaan om een resultaat te kunnen schrijven.

2017-07-05 07:24 UTC, n9iels commented
@barld ik heb een paar wijzigingen gemaakt :-)

2017-07-05 08:48 UTC, barld commented on dbActions/userActions.go
> +		return errors.New("No valid password or email given. Pasword must be at least 8 characters")
of iemand in de database dit email al gebruikt heeft

2017-07-05 08:51 UTC, barld approved these changes

2017-07-05 08:51 UTC, merged